### ISSUE TITLE
Was VAC-Bypass-Loader really patched?

### ISSUE THREAD

**Issue by danielfan61a** [danielkrupinski/VAC-Bypass-Loader#103]
I haven't played CSGO in almost 3 months and I plan on coming back. However, I'm hearing rumors that VAC-Bypass-Loader was patched by Valve or something, is it true ? 

I used to use this + Shtreeba + Osiris with no problems. What changed since then ?

What should I use now ? are there any alternative VAC bypass methods and undetected injectors that work ? ( open source preferably ).

Thank you.

**Comment by Shaxzy** [comment]
I am not sure if there are any alternatives, but Osiris is open source - make it undetected yourself. That way you won't need a vac bypasser.

**Comment by danielfan61a** [comment]
@Shaxzy shut the fuck up.

**Comment by danielfan61a** [comment]
https://github.com/danielkrupinski/Osiris/issues/3313
