### ISSUE TITLE
why does every antivirus detect a trojan horse??

### ISSUE THREAD

**Issue by galpodlipnik1** [danielkrupinski/VAC-Bypass-Loader#104]

**Comment by sestain** [comment]
Most likely because it's injecting a dll from its memory to steam process.

**Comment by galpodlipnik1** [comment]
> Most likely because it's injecting a dll from its memory to steam process.

did u try it. and did it work?

**Comment by sestain** [comment]
> > Most likely because it's injecting a dll from its memory to steam process.
> 
> did u try it. and did it work?

I have compiled the source for vac bypass and vac bypass loader and confirmed that both of them works just fine since they were released few years ago.

**Comment by galpodlipnik1** [comment]
> > > Most likely because it's injecting a dll from its memory to steam process.
> > 
> > 
> > did u try it. and did it work?
> 
> I have compiled the source for vac bypass and vac bypass loader and confirmed that both of them works just fine since they were released few years ago.

thanks

**Comment by Salakksson** [comment]
when i launch VAC-Bypass-Loader.exe it makes an error noise and doesnt do anything
