### ISSUE TITLE
Latest build can't start steam.

### ISSUE THREAD

**Issue by euseanwoon2016** [danielkrupinski/VAC-Bypass-Loader#11]
When I build it as release, and I run the .exe, very briefly I can see the steam "Updating" dialogue and it closes instantly. I even ran it as administrator. When I used the previous version, it managed to open steam with the success dialogue.

**Comment by danielkrupinski** [comment]
Works well, just checked

**Comment by hugohabicht01** [comment]
The same happens to me, do you have any clue whats causing that? @danielkrupinski 
I'm not using the steam beta, just rebooted. Ran the exe as administrator but Steam doesn't get launched.
Any help would be greatly appreciated

**Comment by rafalohaki** [comment]
weird, works for me
