### ISSUE TITLE
[Discussion] Trust factor 

### ISSUE THREAD

**Issue by tirziz** [danielkrupinski/VAC-Bypass-Loader#12]
I think there is something to do with trust factor here.
I tested with a prime account with and without VAC bypass, and the result is with Bypass on the time find match is very long and I met alot of party with obv cheater.
Is there a way, steam detect of VAC is not functional?

**Comment by danielkrupinski** [comment]
Yeah, this is possible as with bypass scan results with module initialization error which is sent to VAC server.

**Comment by EGTLoneWolf** [comment]
so currently this is a theory ? or confirmed?

**Comment by tirziz** [comment]
> so currently this is a theory ? or confirmed?

I have no idea about this matter or how to prove it. Anyway,  It is not the purpose of this project anyway.

**Comment by tirziz** [comment]
I don't think there is no need of further discussion here.
//Close
