### ISSUE TITLE
does it still work?

### ISSUE THREAD

**Issue by idioticisme** [danielkrupinski/VAC-Bypass-Loader#15]

**Comment by arthures11** [comment]
don't think so

**Comment by ZPDMiller** [comment]
Don't see why not

**Comment by idioticisme** [comment]
ppl are talking about it got fixed after last "vac update"

**Comment by tirziz** [comment]
Try it with a detected cheat dude . csgo is free you can generate as many account as you want.

**Comment by idioticisme** [comment]
> Try it with a detected cheat dude . csgo is free you can generate as many account as you want.

please say smth on topic
i just asked if someone knows

**Comment by ZPDMiller** [comment]
Yes it still works

**Comment by itchy2019** [comment]
Yes, still works

**Comment by danielkrupinski** [comment]
Yep, tested today.
