### ISSUE TITLE
Don't working

### ISSUE THREAD

**Issue by mtmjr92** [danielkrupinski/VAC-Bypass-Loader#17]
For any reason don't working

**Comment by rafalohaki** [comment]
weird. it's working for me🤗

**Comment by mtmjr92** [comment]
> 
> 
> weird. it's working for me🤗



It generate a .crash file with 0KB and dont run steam.exe

**Comment by danielkrupinski** [comment]
Make sure you are compiling for `Release | x86` configuration.

**Comment by mtmjr92** [comment]
U right, x86 compilation working! thnk u.
