### ISSUE TITLE
Reconnect Internet?

### ISSUE THREAD

**Issue by steel4me** [danielkrupinski/VAC-Bypass-Loader#19]
Hello, in your other repo you write, follow these steps:

1. Close Steam client if open.
2. Disconnect from the internet.
3. Run Steam as Administrator.
4. Inject VAC-Bypass.dll into Steam.exe process.
5. After successful injection messagebox saying Initialization was successful! should appear.
**6. Reconnect to the internet.**
7. Press Retry in steam window saying 'Could not connect to Steam servers'.

I didnt compiled or tested anything atm. But i can't see the part of "Reconnect to the Internet" in the bypass-loader repo / code. If the loader does not take this step, is this step really necessary at all?

**Comment by danielkrupinski** [comment]
You have to disconnect from the internet to be sure VAC hasn't been loaded before you inject bypass. Bypass loader handles process creation and injection for you.
