### ISSUE TITLE
steam not opening

### ISSUE THREAD

**Issue by airleaks3** [danielkrupinski/VAC-Bypass-Loader#2]
hello, steam is not opening when i run vac bypass loader!

**Comment by danielkrupinski** [comment]
Where do you have your steam client installed?

**Comment by airleaks3** [comment]
F drive in program files

**Comment by danielkrupinski** [comment]
Would you mind posting full path to your Steam.exe file?

**Comment by airleaks3** [comment]
F:\Program Files (x86)\Steam\Steam.exe

**Comment by danielkrupinski** [comment]
It looks like Windows takes "Program files" from another drive as default. As for now you can put your steam path there https://github.com/danielkrupinski/VAC-Bypass-Loader/blob/a9f7b23e6bb660a4b3e0b8ed8a0207b2c30cd2b2/VAC-Bypass-Loader/main.c#L113
e.g `if (CreateProcessW(L"F:\\Program Files (x86)\\Steam\\Steam.exe", NULL, NULL, NULL, FALSE, 0, NULL, NULL, &info, &processInfo)) {`.
I will try to counter this issue soon.

**Comment by airleaks3** [comment]
thank you <33
