### ISSUE TITLE
Issue: acc in infinite loading loop

### ISSUE THREAD

**Issue by January-0002** [danielkrupinski/VAC-Bypass-Loader#20]
Happened to people with the dll, happens on loader too... just saying.

Example: stuckon:

Connecting Account: {Accountname}

**Comment by Matt-cloud** [comment]
I had this before and turns out I wasn't running it as an administrator. Just run it as admin and it should probably be fixed (It worked for me atleast)

**Comment by danielkrupinski** [comment]
It's Steam bug I can't fix. Frankly, it never happened to me when using the loader.
