### ISSUE TITLE
Clicked inject, but didn't injected.

### ISSUE THREAD

**Issue by trollman4444** [danielkrupinski/VAC-Bypass-Loader#21]
Clicked inject, but didn't injected. I tried without VAC Bypass, it works. Someone know how to fix this?

**Comment by trollman4444** [comment]
I am using rando injector, when i just veiled injector, it works. Wonder why. Waiting for your reply.

**Comment by AbdallahMehiz** [comment]
Start the injector as an admin

**Comment by trollman4444** [comment]
> Start the injector as an admin
No affect lol

**Comment by asafalroy** [comment]
Same thing happens to me. Using a different injector so that's probably not the case.
With the VAC Bypass the injection isn't working properly while without it it's working excellent.
Does anyone have a solution for this?

**Comment by danielkrupinski** [comment]
Running injector as administrator is the only solution.
