### ISSUE TITLE
VAC error? (SOLVED)

### ISSUE THREAD

**Issue by hkmodd** [danielkrupinski/VAC-Bypass-Loader#27]
Tested it in bot lobby (using Osiris + junk, RandoInjector + Junk) when I try to spinbot for 2 matches in a row it gives me VAC error and kicks me out of lobby
Then I need to restart Steam normally, verify game cache and restart PC to get the game back normally
Not sure if this is caused by VAC-Bypass-Loader

By the way I use Osiris with [RandoInjector](https://github.com/bananasss00/Rando-Injector) and never got the VAC error, so that's why I'm writing here

P.S. With JunkCode in both cheat and injector VAC never caught me in 2 years, just overwatch (in case of blatant) soooooo I would not even need this VAC-bypass-Loader. The cool thing is to mess up with Cheat Engine on CS:GO secured servers lol (most of functions don't work)

**Comment by techzin** [comment]
Anti-Aim Cause VAC Error, don't use this in DeathMatch or Casual.

**Comment by hkmodd** [comment]
Yea I thought it was something like that
