### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by Mike101001** [danielkrupinski/VAC-Bypass-Loader#38]
First of all thank you so much for this! Have you tested this lately?

**Comment by Vadenez** [comment]
I have, and it works great. It stops you from getting banned by vacs automated server from what i understand, and from practise. But be warned you CAN still get overwatch banned, so don't be blantant, and dont hack with your main account.

**Comment by Mike101001** [comment]
Very cool.Thanks!

**Comment by rafalohaki** [comment]
testing it more than half year and it works great
