### ISSUE TITLE
steam client bootstrapper stopped working

### ISSUE THREAD

**Issue by Jeffbeu** [danielkrupinski/VAC-Bypass-Loader#44]
I don't know what is happening when I open it I did all the right steps when the steam program stops responding and doesn't open anything. What did I do wrong?
[https://prnt.sc/t1pgcv](url)

**Comment by Vadenez** [comment]
did you have steam and csgo closed before opening VAC-Bypass?

**Comment by oron-sinaa** [comment]
Check:-
1. If the Steam app or service is not running (through task manager and taskbar apps)
2. If the installation directory is set to C:/Program Files (x86)/Steam... (Not sure about this)
3. Antivirus programs are not blocking the software, if so - Add this to exceptions.

**Comment by Jeffbeu** [comment]
I used DLL VAC-BYPASS and its working thanks for help
