### ISSUE TITLE
use vac bypass loader and new bypass anticheat inject,csgo crash

### ISSUE THREAD

**Issue by mliiyyyyy** [danielkrupinski/VAC-Bypass-Loader#48]
since july 10,when i use vac bypass and onebyteldr inject osiris to csgo,csgo will crash

**Comment by rafalohaki** [comment]
weird, its working for me.

**Comment by mliiyyyyy** [comment]
hm，maybe is my problem

**Comment by mliiyyyyy** [comment]
idk how to fix this error，even i used pure Osiris, vac bypass and onbyteldr

**Comment by MasterChief220** [comment]
problem is with your injector i think

**Comment by mliiyyyyy** [comment]
OK . i find the solution , disable UAC and enjoy it
