### ISSUE TITLE
Steam Client Bootstrapper Stopped Working

### ISSUE THREAD

**Issue by zxsleebu** [danielkrupinski/VAC-Bypass-Loader#49]
On Windows 1607 it doesn't work. On 19H2 it works.

**Comment by rafalohaki** [comment]
click windows update...

**Comment by zxsleebu** [comment]
lol no. my pc is so sh1t, and on 19h2 the file explorer open up in 16 seconds

**Comment by zxsleebu** [comment]
i'll try to code my version of vac bypass loader from zero. no paste, only handwritten code xd (lol jk it will be paste)

**Comment by zxsleebu** [comment]
[done.](https://github.com/zxsleebu/FuckThatVAC) works like a charm

**Comment by zxsleebu** [comment]
I think I can close this issue, cuz dev doesn’t read them lol
