### ISSUE TITLE
Visual Studio Components

### ISSUE THREAD

**Issue by sonny2589** [danielkrupinski/VAC-Bypass-Loader#57]
Can anyone help me which components to select when installing Visual Studio 2019 to compile VAC Bypass Loader. Because If I select all components it will be around 19 GB

**Comment by went-pogfishing** [comment]
in the readme it says you need Windows SDK 10.0

**Comment by danielkrupinski** [comment]
> For core C and C++ support, choose the "Desktop development with C++" workload.
