### ISSUE TITLE
How to remove the "Initialization was successful" when it bypasses the vac?

### ISSUE THREAD

**Issue by 0xb77a9** [danielkrupinski/VAC-Bypass-Loader#61]

**Comment by Gangster8192** [comment]
Compile vac-bypass yourself (not vac-bypass-loader) and remove the messagebox.

**Comment by 0xb77a9** [comment]
> Compile vac-bypass yourself (not vac-bypass-loader) and remove the messagebox.

thank you alot it was jst about the dll to hex but my friend helped me

Thanks.
