### ISSUE TITLE
Not working, CSGO and Steam still show VAC ban

### ISSUE THREAD

**Issue by JhonnyAndreatta** [danielkrupinski/VAC-Bypass-Loader#63]
I turned off my internet, ran the vac bypass in Admin mode, turned the internet back on and logged in, but when I open the CSGO the game still says that I got VAC Ban, and when I open the steam panel it still shows the that I got 1 VAC ban. 
I compiled the code on VS 2019 in Release x86.

![ptr](https://user-images.githubusercontent.com/53795172/97501765-9d2d4580-1950-11eb-90ef-789d83ac6e3b.png)

**Comment by HTT5041** [comment]
Hey, I don’t think you understand what this code does. As far as I’m aware, this is meant to allow cheats to bypass VAC completely - not remove VAC bans as only steam can do that.

**Comment by 0xb77a9** [comment]
xDDDD

**Comment by rafalohaki** [comment]
xDDDDDDD

**Comment by n0dzzz** [comment]
LMAO

**Comment by wemanzoz** [comment]
LMFAO WTF

**Comment by JhonnyAndreatta** [comment]
xD

**Comment by jiahao2333** [comment]
XD

**Comment by techzin** [comment]
LMAO

**Comment by CrazyCSIW6** [comment]
Top 10 Dumbest GitHub Issues

**Comment by CrazyCSIW6** [comment]
> xD

man, OP has the balls to laugh at himself like that. props

**Comment by rafalohaki** [comment]
![image](https://user-images.githubusercontent.com/20607107/211772406-86f45d85-9ea0-44aa-be95-60e04cf61424.png)
when someone writes in dead chat
