### ISSUE TITLE
Patched?

### ISSUE THREAD

**Issue by wemanzoz** [danielkrupinski/VAC-Bypass-Loader#66]
https://pays.host/M2ulkvLD_

@danielkrupinski

**Comment by yourmom-jpeg** [comment]
same here

**Comment by sotakoira** [comment]
me and my friends were using otcv3, shtreeba and vac bypass loader, today we all got booted to [this page](https://support.steampowered.com/kb_article.php?ref=2117-ILZV-2837). No problems before at all

edit: sounds like otcv3 doesn't run aimstep in casual servers anymore

**Comment by iloev** [comment]
> me and my friends were using otcv3, shtreeba and vac bypass loader, today we all got booted to [this page](https://support.steampowered.com/kb_article.php?ref=2117-ILZV-2837). No problems before at all
> 
> edit: sounds like otcv3 doesn't run aimstep in casual servers anymore

otc2 dont run aimstep in casual anymore,already got 2 vac errors lol '-'
