### ISSUE TITLE
Apparently the VAC Bypass Loader does not work anymore?

### ISSUE THREAD

**Issue by AverageShade** [danielkrupinski/VAC-Bypass-Loader#72]
I have heard that the VAC Bypass Loader no longer works or is detected, is that true? Or does that only apply to some other version?

**Comment by OzymoGit** [comment]
source?

**Comment by AverageShade** [comment]
> 
> 
> source?

Some people were saying that in a Discord server for an injector. Apparently it was patched.

**Comment by 0xE232FE** [comment]
VAC Error caused by corrupted game files. Please verify your Gamefiles before join a VAC Secured Server. :-)

And the VAC Bypass still working, there is no VAC Module for scanning for WINAPI Hooks atm.

**Comment by AverageShade** [comment]
> 
> 
> VAC Error caused by corrupted game files. Please verify your Gamefiles before join a VAC Secured Server. :-)
> 
> And the VAC Bypass still working, there is no VAC Module for scanning for WINAPI Hooks atm.

I see, thank you for the reply
