### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by wmcnamara** [danielkrupinski/VAC-Bypass-Loader#85]
The code is not documented so I struggle to understand how this works. Could someone explain it to me?

**Comment by Zman2024** [comment]
from: https://github.com/danielkrupinski/VAC-Bypass/

## How it works
The goal is to make https://github.com/danielkrupinski/VAC/blob/2eeb40e38d0f0d7b828dbacb663ee00aef15c1ca/VAC/Utils.c#L187
function return `false` then VAC aborts scan for cheats. It can be done by bypassing [this check](https://github.com/danielkrupinski/VAC/blob/2eeb40e38d0f0d7b828dbacb663ee00aef15c1ca/VAC/Utils.c#L195) for example.
