### ISSUE TITLE
I want to make the VAC-Bypass start steam with parameters "-no-browser +open steam://open/minigameslist"

### ISSUE THREAD

**Issue by Ryuo1** [danielkrupinski/VAC-Bypass-Loader#91]
I have a low-end computer. So I use steam with -no-browser command which reduces the memory usage of steam. I tried looking in the .sln file but couldn't understand anything. Can anyone tell me how do I [title]?

**Comment by Shaxzy** [comment]
Can't you just manually put the parameter in the launch options or just disable the steam overlay?

**Comment by Ryuo1** [comment]
> Can't you just manually put the parameter in the launch options or just disable the steam overlay?

How do I do it?

**Comment by Zman2024** [comment]
all parameters that are passed to the loader are passed to steam. Just send -no-browser to the loader via shortcut / batch script

**Comment by Ryuo1** [comment]
> all parameters that are passed to the loader are passed to steam. Just send -no-browser to the loader via shortcut / batch script

I am not good in Visual Studio I just installed it some days ago. When I tried to open the .sln file, I couldn't find any code where it opens steam.

**Comment by HackerPide** [comment]
> > all parameters that are passed to the loader are passed to steam. Just send -no-browser to the loader via shortcut / batch script
> 
> I am not good in Visual Studio I just installed it some days ago. When I tried to open the .sln file, I couldn't find any code where it opens steam.

@Taughtimp2786 
No need to edit the source code, didnt test myself but this should work(according to https://github.com/danielkrupinski/VAC-Bypass-Loader/issues/91#issuecomment-855307915):
`VAC-Bypass-Loader.exe -no-browser`

**Comment by Ryuo1** [comment]
> > > all parameters that are passed to the loader are passed to steam. Just send -no-browser to the loader via shortcut / batch script
> > 
> > I am not good in Visual Studio I just installed it some days ago. When I tried to open the .sln file, I couldn't find any code where it opens steam.
> 
> @Taughtimp2786 
> No need to edit the source code, didnt test myself but this should work(according to https://github.com/danielkrupinski/VAC-Bypass-Loader/issues/91#issuecomment-855307915):
> `VAC-Bypass-Loader.exe -no-browser`

It works! Thank you so much.
