### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ENDER1355** [danielkrupinski/VAC-Bypass-Loader#96]
1. Does it work for TF2?
2. Still undetected?
3. How do I set it up?

If I get yes from all of these questions, I will give this 5 stars

**_go back to Minecraft!!111_** (please don't say this)

**Comment by floydGG** [comment]
1. Yes
2. Yes
3. Compile it with Visual Studio 2019 and run the exe.

**Comment by ENDER1355** [comment]
> 1. Yes
> 2. Yes
> 3. Compile it with Visual Studio 2019 and run the exe.

change my mind 1000000/1 stars
